Install neoadmin library and display a login page
neocodevs/neoadmin-demo pull request #6
Opened 2023-02-02 18:23 UTC by victor-gv

2023-02-02 18:24 UTC, victor-gv commented on src/pages/Login/headers.tsx
> +      component: (props: any) => <Login {...props} onSubmit={loginRequest} />,
@xavi-tristancho he posat type "any", no sé bé com s'hauria de tipar aquest cas.

2023-02-03 09:09 UTC, xavi-tristancho requested changes

2023-02-03 09:09 UTC, xavi-tristancho commented on src/pages/Login/headers.tsx
> +  });
@victor-gv it's easier to do 

```
return Promise.resolve({
  user: {
    name: "test",
    email: "test@mail.com",
  },
  token: "test",
})
```

2023-02-07 12:37 UTC, xavi-tristancho requested changes

2023-02-07 12:37 UTC, xavi-tristancho commented on src/pages/Login/headers.tsx
> +      component: (props: any) => <Login {...props} onSubmit={loginRequest} />,
@victor-gv falta la prop `auth` a `false`

2023-02-07 12:43 UTC, xavi-tristancho approved these changes

2023-02-07 12:43 UTC, merged